const urlInput=document.getElementById("urlInput"),playlistInput=document.getElementById("playlistInput"),fileInput=document.getElementById("fileInput"),addUrlBtn=document.getElementById("addUrlBtn"),clearBtn=document.getElementById("clearBtn"),channelList=document.getElementById("channelList"),count=document.getElementById("count"),search=document.getElementById("search"),video=document.getElementById("video"),playerEmpty=document.getElementById("playerEmpty"),currentLogo=document.getElementById("currentLogo"),currentName=document.getElementById("currentName"),currentGroup=document.getElementById("currentGroup"),status=document.getElementById("status"),techStatus=document.getElementById("techStatus"),quality=document.getElementById("quality"),dataSaver=document.getElementById("dataSaver");let channels=[],currentChannel=null,hls=null,dash=null;
function parseM3U(text){const lines=text.replace(/\r/g,"").split("\n").map(x=>x.trim()).filter(Boolean),result=[];for(let i=0;i<lines.length;i++){if(!lines[i].startsWith("#EXTINF"))continue;const info=lines[i],url=lines[i+1];if(!url||url.startsWith("#"))continue;const nm=info.match(/tvg-name="([^"]*)"/i),lm=info.match(/tvg-logo="([^"]*)"/i),gm=info.match(/group-title="([^"]*)"/i);let name=nm?nm[1]:"";if(!name){const comma=info.indexOf(",");name=comma>=0?info.substring(comma+1).trim():"Unknown Channel"}result.push({id:crypto.randomUUID(),name,url,logo:lm?lm[1]:"",group:gm?gm[1]:"General",online:"checking"})}return result}
function addChannels(items){if(!items.length)return setStatus("No channels found",true);channels.push(...items);renderChannels();setStatus(`${items.length} channels imported`);checkAllChannels()}
addUrlBtn.addEventListener("click",async()=>{const url=urlInput.value.trim();if(!url)return;setStatus("Loading playlist...");try{const r=await fetch(url);if(!r.ok)throw Error();const text=await r.text(),parsed=parseM3U(text);if(parsed.length)addChannels(parsed);else addChannels([{id:crypto.randomUUID(),name:"Stream",url,logo:"",group:"Direct Stream",online:"checking"}])}catch(e){addChannels([{id:crypto.randomUUID(),name:"Stream",url,logo:"",group:"Direct Stream",online:"checking"}]);setStatus("Added as direct stream")}urlInput.value=""});
playlistInput.addEventListener("input",()=>{const text=playlistInput.value.trim();if(!text||!text.includes("#EXTINF"))return;channels=parseM3U(text);renderChannels();setStatus(`${channels.length} channels loaded`);checkAllChannels()});
fileInput.addEventListener("change",async()=>{const file=fileInput.files[0];if(!file)return;channels=parseM3U(await file.text());renderChannels();setStatus(`${channels.length} channels imported`);checkAllChannels()});
function renderChannels(filter=""){channelList.innerHTML="";const q=filter.toLowerCase(),visible=channels.filter(c=>c.name.toLowerCase().includes(q)||c.group.toLowerCase().includes(q));count.textContent=channels.length;if(!visible.length){channelList.innerHTML='<div class="empty">No channels found.</div>';return}visible.forEach(c=>{const card=document.createElement("div");card.className="channel-card"+(currentChannel?.id===c.id?" active-channel":"");const sc=c.online===true?"online":c.online===false?"offline":"checking",st=c.online===true?"Online":c.online===false?"Offline":"Checking";card.innerHTML=`<div class="channel-main"><div class="channel-logo">${c.logo?`<img src="${escapeHTML(c.logo)}" alt="" onerror="this.style.display='none'">`:'<span class="logo-placeholder">TV</span>'}</div><div class="channel-info"><div class="channel-name">${escapeHTML(c.name)}</div><div class="channel-group">${escapeHTML(c.group)}</div><div class="channel-status ${sc}"><span class="status-dot"></span>${st}</div></div></div><button class="delete-channel" title="Delete channel">×</button>`;card.addEventListener("click",e=>{if(!e.target.closest(".delete-channel"))selectChannel(c)});card.querySelector(".delete-channel").addEventListener("click",e=>{e.stopPropagation();deleteChannel(c.id)});channelList.appendChild(card)})}
function deleteChannel(id){if(currentChannel?.id===id){stopPlayer();currentChannel=null;currentName.textContent="No channel selected";currentGroup.textContent="—";currentLogo.hidden=true;playerEmpty.style.display="flex"}channels=channels.filter(c=>c.id!==id);renderChannels(search.value);setStatus("Channel deleted")}
search.addEventListener("input",()=>renderChannels(search.value));
function selectChannel(c){currentChannel=c;renderChannels(search.value);currentName.textContent=c.name;currentGroup.textContent=c.group||"—";if(c.logo){currentLogo.src=c.logo;currentLogo.hidden=false}else currentLogo.hidden=true;playerEmpty.style.display="none";playStream(c);setStatus(`Playing ${c.name}`)}
function playStream(c){stopPlayer();const url=c.url,isM3U8=/\.m3u8($|\?)/i.test(url),isMPD=/\.mpd($|\?)/i.test(url);if(isM3U8&&typeof Hls!=="undefined"&&Hls.isSupported()){hls=new Hls({enableWorker:true,capLevelToPlayerSize:dataSaver.checked,maxBufferLength:dataSaver.checked?10:30,maxMaxBufferLength:dataSaver.checked?20:60});hls.loadSource(url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>{setupHlsQuality();video.play().catch(()=>{})});hls.on(Hls.Events.ERROR,(e,d)=>{if(d.fatal)setStatus("Stream error",true)});techStatus.textContent="HLS.js active";return}if(isMPD&&typeof dashjs!=="undefined"){dash=dashjs.MediaPlayer().create();dash.initialize(video,url,true);dash.on(dashjs.MediaPlayer.events.STREAM_INITIALIZED,setupDashQuality);techStatus.textContent="DASH.js active";return}video.src=url;video.play().catch(()=>{});techStatus.textContent="Native video player"}
function setupHlsQuality(){quality.innerHTML='<option value="auto">Auto / Adaptive</option>';if(!hls)return;const map=new Map();hls.levels.forEach((l,i)=>{if(l.height){const q=findClosestQuality(l.height);if(!map.has(q))map.set(q,i)}});[144,240,360,720,1080].forEach(q=>{if(map.has(q)){const o=document.createElement("option");o.value=map.get(q);o.textContent=q+"p";quality.appendChild(o)}})}
function setupDashQuality(){quality.innerHTML='<option value="auto">Auto / Adaptive</option>';try{const map=new Map();dash.getBitrateInfoListFor("video").forEach((x,i)=>{if(x.height){const q=findClosestQuality(x.height);if(!map.has(q))map.set(q,i)}});[144,240,360,720,1080].forEach(q=>{if(map.has(q)){const o=document.createElement("option");o.value="dash-"+map.get(q);o.textContent=q+"p";quality.appendChild(o)}})}catch(e){}}
quality.addEventListener("change",()=>{const v=quality.value;if(v==="auto"){if(hls)hls.currentLevel=-1;if(dash)try{dash.updateSettings({streaming:{abr:{autoSwitchBitrate:{video:true}}}})}catch(e){}return}if(hls){const n=Number(v);if(!Number.isNaN(n))hls.currentLevel=n;return}if(dash&&v.startsWith("dash-")){try{dash.updateSettings({streaming:{abr:{autoSwitchBitrate:{video:false}}}});dash.setRepresentationForTypeByIndex("video",Number(v.slice(5)))}catch(e){}}});
dataSaver.addEventListener("change",()=>{if(!hls)return;hls.config.capLevelToPlayerSize=dataSaver.checked;hls.config.maxBufferLength=dataSaver.checked?10:30;hls.config.maxMaxBufferLength=dataSaver.checked?20:60});
async function checkChannel(c){const v=document.createElement("video");v.muted=true;v.preload="metadata";let done=false;const finish=online=>{if(done)return;done=true;c.online=online;renderChannels(search.value)};const timer=setTimeout(()=>{finish(false);v.remove()},8000);v.addEventListener("loadedmetadata",()=>{clearTimeout(timer);finish(true);v.remove()});v.addEventListener("canplay",()=>{clearTimeout(timer);finish(true);v.remove()});v.addEventListener("error",()=>{clearTimeout(timer);finish(false);v.remove()});v.src=c.url;try{v.load()}catch(e){clearTimeout(timer);finish(false)}}
function checkAllChannels(){channels.forEach((c,i)=>setTimeout(()=>checkChannel(c),i*250))}
function stopPlayer(){if(hls){try{hls.destroy()}catch(e){}hls=null}if(dash){try{dash.reset()}catch(e){}dash=null}video.pause();video.removeAttribute("src");video.load();quality.innerHTML='<option value="auto">Auto / Adaptive</option>'}
clearBtn.addEventListener("click",()=>{stopPlayer();channels=[];currentChannel=null;renderChannels();currentName.textContent="No channel selected";currentGroup.textContent="—";currentLogo.hidden=true;playerEmpty.style.display="flex";playlistInput.value="";urlInput.value="";setStatus("Cleared")});
function setStatus(message,error=false){status.textContent=message;status.classList.toggle("error",error)}function findClosestQuality(h){const qs=[144,240,360,720,1080];return qs.reduce((a,b)=>Math.abs(b-h)<Math.abs(a-h)?b:a)}function escapeHTML(v){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
